services:
  db:
    image: postgres:16
    container_name: fpl-playmaker-db
    restart: always
    environment:
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD} # choose a password you like
      POSTGRES_DB: ${POSTGRES_DB}          # name of your app DB
    ports:
      - "5433:5432"
    volumes:
      - db_data:/var/lib/postgresql/data

volumes:
  db_data:
